In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

# AREA

In [3]:
#ben_cost=pd.read_csv('../data/Benefits_Cost_Sharing_PUF.csv',low_memory=False, encoding ='latin1')
#rules=pd.read_csv('../data/Business_Rules_PUF.csv',low_memory=False, encoding ='latin1')
#network=pd.read_csv('../data/Network_PUF.csv',low_memory=False, encoding ='latin1')
#attr=pd.read_csv('../data/Plan_Attributes_PUF.csv',low_memory=False, encoding ='latin1')
#rate=pd.read_csv('../data/Rate_PUF.csv',low_memory=False, encoding ='latin1')
area=pd.read_csv('../data/raw_files/Service_Area_PUF.csv',low_memory=False, encoding ='latin1')

In [4]:
#this gets rid of the Dental Only Plans leaving medical insurance plans then drops the column as superfilous
area=area[area.DentalOnlyPlan != 'Yes']
area.drop('DentalOnlyPlan', axis=1, inplace=True)

area=area.drop(['BusinessYear','SourceName', 'ImportDate'], axis = 1)
area.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5643 entries, 0 to 11304
Data columns (total 10 columns):
StateCode                     5643 non-null object
IssuerId                      5643 non-null int64
ServiceAreaId                 5643 non-null object
ServiceAreaName               5643 non-null object
CoverEntireState              5643 non-null object
County                        5598 non-null float64
PartialCounty                 5598 non-null object
ZipCodes                      53 non-null object
PartialCountyJustification    53 non-null object
MarketCoverage                5643 non-null object
dtypes: float64(1), int64(1), object(8)
memory usage: 484.9+ KB

In [5]:
# grab states w/ zipcode level plans

zipcodes=area[area.ZipCodes.isnull() == False]

In [6]:
area_FL=area[area.StateCode == 'FL'].copy()
'''
EDA shows FL does not have  plans based on 'PartialCounty', ''ZipCodes', or
PartialCountyJustification' so they are being dropped
'''

area_FL=area_FL.drop(['PartialCounty', 'ZipCodes', 'PartialCountyJustification'], axis = 1)

''' only offer Individual plans so that column is being dropped'''
area_FL=area_FL.drop('MarketCoverage', axis = 1)

In [7]:
in_state= area_FL[area_FL.CoverEntireState== 'Yes']
uniques={} 
for col in area_FL.columns: 
    uniques[col]=area_FL[col].unique()
uniques
county_list=uniques['County']

for county in county_list:
    list1=['FL','16842','FLS001','BlueOptions','Yes']
    list1.append(county)
    area_FL = area_FL.append(pd.Series(list1, index=area_FL.columns ), ignore_index=True)

In [8]:
#dropna has to be done post split
area_FL=area_FL.dropna()
area_FL['IssuerId']=area_FL['IssuerId'].astype(int)
area_FL['County']=area_FL['County'].astype(int)
area_FL.drop(['StateCode','ServiceAreaName','CoverEntireState'],axis=1,inplace=True)

area_FL.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 213 entries, 0 to 214
Data columns (total 3 columns):
IssuerId         213 non-null int32
ServiceAreaId    213 non-null object
County           213 non-null int32
dtypes: int32(2), object(1)
memory usage: 5.0+ KB

In [9]:
area_FL

     IssuerId ServiceAreaId  County
0       12379        FLS001   12095
1       12379        FLS001   12117
2       12379        FLS001   12097
3       12379        FLS001   12069
4       12379        FLS001   12127
5       12379        FLS003   12101
6       12379        FLS003   12057
7       12379        FLS003   12103
8       12379        FLS002   12031
9       12379        FLS002   12019
10      12379        FLS002   12033
11      12379        FLS002   12113
12      12379        FLS004   12099
14      16842        FLS002   12003
15      16842        FLS002   12005
16      16842        FLS002   12009
17      16842        FLS002   12011
18      16842        FLS002   12015
19      16842        FLS002   12017
20      16842        FLS002   12019
21      16842        FLS002   12031
22      16842        FLS002   12033
23      16842        FLS002   12045
24      16842        FLS002   12053
25      16842        FLS002   12055
26      16842        FLS002   12057
27      16842        FLS002   12061
28      16842        FLS002   12069
29      16842        FLS002   12083
30      16842        FLS002   12085
31      16842        FLS002   12086
32      16842        FLS002   12091
33      16842        FLS002   12095
34      16842        FLS002   12097
35      16842        FLS002   12099
36      16842        FLS002   12101
37      16842        FLS002   12103
38      16842        FLS002   12105
39      16842        FLS002   12109
40      16842        FLS002   12113
41      16842        FLS002   12115
42      16842        FLS002   12117
43      16842        FLS002   12119
44      16842        FLS002   12131
45      21663        FLS001   12001
46      21663        FLS001   12009
47      21663        FLS001   12011
48      21663        FLS001   12015
49      21663        FLS001   12017
50      21663        FLS001   12019
51      21663        FLS001   12031
52      21663        FLS001   12033
53      21663        FLS001   12035
54      21663        FLS001   12053
55      21663        FLS001   12055
56      21663        FLS001   12057
57      21663        FLS001   12069
58      21663        FLS001   12081
59      21663        FLS001   12083
60      21663        FLS002   12086
61      21663        FLS001   12091
62      21663        FLS001   12093
63      21663        FLS001   12095
64      21663        FLS001   12097
65      21663        FLS003   12099
66      21663        FLS001   12101
67      21663        FLS001   12103
68      21663        FLS001   12105
69      21663        FLS001   12107
70      21663        FLS001   12111
71      21663        FLS001   12115
72      21663        FLS001   12117
73      21663        FLS001   12127
74      21663        FLS001   12131
75      30252        FLS001   12001
76      30252        FLS001   12003
77      30252        FLS001   12005
78      30252        FLS001   12007
79      30252        FLS001   12009
80      30252        FLS001   12015
81      30252        FLS001   12017
82      30252        FLS001   12019
83      30252        FLS001   12021
84      30252        FLS001   12023
85      30252        FLS001   12027
86      30252        FLS001   12029
87      30252        FLS001   12033
88      30252        FLS001   12035
89      30252        FLS001   12041
90      30252        FLS001   12051
91      30252        FLS001   12053
92      30252        FLS001   12069
93      30252        FLS001   12071
94      30252        FLS001   12075
95      30252        FLS001   12081
96      30252        FLS001   12083
97      30252        FLS001   12085
98      30252        FLS001   12089
99      30252        FLS001   12091
100     30252        FLS001   12093
101     30252        FLS001   12109
102     30252        FLS001   12111
103     30252        FLS001   12113
104     30252        FLS001   12115
105     30252        FLS001   12119
106     30252        FLS001   12121
107     30252        FLS001   12127
108     30252        FLS001   12131
109     30252        FLS002   12001
110     30252        FLS002   12011
111     30252        FLS002   12015
112     30252        FLS002   12017
113     30252        FLS002   12031
114     30252        FLS002   12057
115     30252        FLS002   12081
116     30252        FLS002   12085
117     30252        FLS002   12086
118     30252        FLS002   12095
119     30252        FLS002   12097
120     30252        FLS002   12099
121     30252        FLS002   12101
122     30252        FLS002   12103
123     30252        FLS002   12105
124     30252        FLS002   12107
125     30252        FLS002   12111
126     30252        FLS002   12117
127     30252        FLS003   12089
128     36194        FLS001   12009
129     36194        FLS002   12035
130     36194        FLS002   12127
131     36194        FLS002   12117
132     40572        FLS001   12035
133     40572        FLS001   12127
134     40572        FLS001   12011
135     40572        FLS001   12086
136     40572        FLS001   12099
137     40572        FLS001   12083
138     40572        FLS001   12053
139     40572        FLS001   12057
140     40572        FLS001   12101
141     40572        FLS001   12103
142     40572        FLS001   12069
143     40572        FLS001   12095
144     40572        FLS001   12097
145     40572        FLS001   12117
146     48121        FLS001   12021
147     48121        FLS002   12099
148     54172        FLS001   12011
149     54172        FLS001   12031
150     54172        FLS001   12057
151     54172        FLS001   12086
152     54172        FLS001   12097
153     54172        FLS001   12099
154     54172        FLS001   12103
155     54172        FLS001   12105
156     54172        FLS001   12019
157     54172        FLS001   12101
158     54172        FLS001   12095
159     54172        FLS001   12117
160     56503        FLS001   12009
161     56503        FLS001   12035
162     56503        FLS001   12109
163     56503        FLS001   12117
164     56503        FLS001   12127
165     16842        FLS001   12095
166     16842        FLS001   12117
167     16842        FLS001   12097
168     16842        FLS001   12069
169     16842        FLS001   12127
170     16842        FLS001   12101
171     16842        FLS001   12057
172     16842        FLS001   12103
173     16842        FLS001   12031
174     16842        FLS001   12019
175     16842        FLS001   12033
176     16842        FLS001   12113
177     16842        FLS001   12099
179     16842        FLS001   12003
180     16842        FLS001   12005
181     16842        FLS001   12009
182     16842        FLS001   12011
183     16842        FLS001   12015
184     16842        FLS001   12017
185     16842        FLS001   12045
186     16842        FLS001   12053
187     16842        FLS001   12055
188     16842        FLS001   12061
189     16842        FLS001   12083
190     16842        FLS001   12085
191     16842        FLS001   12086
192     16842        FLS001   12091
193     16842        FLS001   12105
194     16842        FLS001   12109
195     16842        FLS001   12115
196     16842        FLS001   12119
197     16842        FLS001   12131
198     16842        FLS001   12001
199     16842        FLS001   12035
200     16842        FLS001   12081
201     16842        FLS001   12093
202     16842        FLS001   12107
203     16842        FLS001   12111
204     16842        FLS001   12007
205     16842        FLS001   12021
206     16842        FLS001   12023
207     16842        FLS001   12027
208     16842        FLS001   12029
209     16842        FLS001   12041
210     16842        FLS001   12051
211     16842        FLS001   12071
212     16842        FLS001   12075
213     16842        FLS001   12089
214     16842        FLS001   12121

## FIPS

In [10]:
#this works

fips= pd.read_csv('../data/zipcodes-county-fips-crosswalk/ZIP-COUNTY-FIPS_2017-06.csv',  dtype='str')
fips['STCOUNTYFP']=fips['STCOUNTYFP'].astype(int)
fips['COUNTYNAME'] = fips['COUNTYNAME'].str.replace(r' County', '')
#fips[['County','County_Name']]=fips[['STCOUNTYFP','COUNTYNAME']]
fips = fips[fips.STATE== 'FL']

#fips.reset_index(inplace=True)

FL_zips =pd.DataFrame()
FL_zips[['zipcode','County','County_Name']] = fips[['ZIP','STCOUNTYFP','COUNTYNAME']]

FL_zips.to_csv('../data/clean_files/zipcodes.csv')

FL_county =pd.DataFrame()
FL_county[['County','County_Name']] = fips[['STCOUNTYFP','COUNTYNAME']]


FL_county.sort_values(by=['County'])
FL_county=FL_county.drop_duplicates(keep='first')
result = pd.merge(area_FL,FL_county, how='left', on=['County', 'County'])
#pd.merge(area_FL, FL_county, how='left', left='County',right='County')

# result.to_csv('../data/clean_files/area_FL.csv')

# result

In [11]:
FL_zips

     zipcode  County County_Name
7096   32609   12001     Alachua
7097   32622   12001     Alachua
7098   32633   12001     Alachua
7099   32044   12001     Alachua
7100   32612   12001     Alachua
...      ...     ...         ...
8675   32425   12133  Washington
8676   32431   12133  Washington
8677   32427   12133  Washington
8678   32463   12133  Washington
8679   32462   12133  Washington

[1584 rows x 3 columns]

## combine the two

In [12]:
area_FL=pd.merge(FL_zips,area_FL,how='left', on='County')
area_FL.to_csv('../data/clean_files/area_FL.csv')

In [13]:
area_FL.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7972 entries, 0 to 7971
Data columns (total 5 columns):
zipcode          7972 non-null object
County           7972 non-null int32
County_Name      7972 non-null object
IssuerId         7840 non-null float64
ServiceAreaId    7840 non-null object
dtypes: float64(1), int32(1), object(3)
memory usage: 342.5+ KB

In [14]:
area_FL

     zipcode  County County_Name  IssuerId ServiceAreaId
0      32609   12001     Alachua   21663.0        FLS001
1      32609   12001     Alachua   30252.0        FLS001
2      32609   12001     Alachua   30252.0        FLS002
3      32609   12001     Alachua   16842.0        FLS001
4      32622   12001     Alachua   21663.0        FLS001
...      ...     ...         ...       ...           ...
7967   32425   12133  Washington       NaN           NaN
7968   32431   12133  Washington       NaN           NaN
7969   32427   12133  Washington       NaN           NaN
7970   32463   12133  Washington       NaN           NaN
7971   32462   12133  Washington       NaN           NaN

[7972 rows x 5 columns]